name: Too Much of a Person
title: Too Much of a Person
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/DeckOfPandas/too-much-of-a-person-test/" # the base hostname & protocol for your site
markdown: kramdown
# kramdown: 
#  parse_block_html: true
highlighter: null
sass:
    style: compressed
plugins:
  - jekyll-redirect-from
future: true

collections:
  blog:
    output: true
    permalink: /:collection/:year/:month/:day/:title
  events:
    output: true
    permalink: /:collection/:year/:month/:title
  interviiews:
    output: true
    permalink: /:collection/:path
  sponsors:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "blog_post"
  -
    scope:
      path: ""
      type: "interviews"
    values:
      layout: "interviews"
      header_image: datasets_img.jpg
      image_credit: 
        - Credit: "NAME"
          URL: "#"
          Licence: "CC BY-NC"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

repository: too-much-of-a-person-test